import { App, MarkdownRenderChild, Modal, Notice } from "obsidian";
import { RenderResult } from "../core/types";
import { RenderService } from "../core/render-service";
import { ExportService } from "../core/export-service";
import { TikzHistoryStore } from "../core/history";
import { DisplayTheme, TikzSettings } from "../settings/settings";

type TikzViewState = { zoom: number; panX: number; panY: number };

export class TikzRendererView extends MarkdownRenderChild {
  private cleanup?: () => void;
  private static readonly activeViews = new Map<string, TikzRendererView>();
  private static readonly allViews = new Set<TikzRendererView>();
  private static readonly viewStates = new Map<string, TikzViewState>();

  constructor(private readonly app: App, private readonly exportService: ExportService, host: HTMLElement, private readonly result: RenderResult, private readonly source: string, private readonly sourcePath: string, private readonly service: RenderService, private readonly kind: RenderResult["kind"], private readonly history: TikzHistoryStore, private readonly historyKey: string, private readonly editSource: (source: string) => Promise<void>, private readonly getSettings: () => TikzSettings, private readonly saveSettings: (settings: TikzSettings) => Promise<void>) { super(host); }

  render(): void {
    this.cleanup?.();
    const stateKey = `${this.sourcePath}::${this.historyKey}`;
    const previous = TikzRendererView.activeViews.get(stateKey);
    if (previous && previous !== this) previous.dispose(false);
    TikzRendererView.activeViews.set(stateKey, this);
    TikzRendererView.allViews.add(this);
    this.containerEl.empty();
    const doc = this.containerEl.ownerDocument; const win = doc.defaultView;
    const shell = this.containerEl.createDiv({ cls: "tikz-renderer-shell" });
    const viewport = shell.createDiv({ cls: "tikz-renderer-viewport" });
    const parsed = new DOMParser().parseFromString(this.result.svg, "image/svg+xml");
    if (parsed.querySelector("parsererror") || parsed.documentElement.tagName.toLowerCase() !== "svg") throw new Error("The TeX renderer produced invalid SVG output.");
    const svg = doc.importNode(parsed.documentElement, true) as unknown as SVGSVGElement;
    svg.classList.add("tikz-renderer-svg"); svg.setAttribute("role", "img"); svg.setAttribute("aria-label", "TikZ diagram"); svg.setAttribute("draggable", "false"); viewport.appendChild(svg);

    const controls = shell.createDiv({ cls: "tikz-renderer-controls" });
    const menu = controls.createEl("button", { cls: "tikz-renderer-menu", text: "⋯", attr: { type: "button", title: "TikZ controls", "aria-label": "TikZ controls", "aria-expanded": "false" } });
    const panel = doc.body.createDiv({ cls: "tikz-renderer-panel" }); panel.hidden = true; panel.setAttribute("role", "menu"); panel.dataset.tikzPopup = "true";
    const persisted = TikzRendererView.viewStates.get(stateKey) ?? loadViewState(stateKey); if (persisted) TikzRendererView.viewStates.set(stateKey, persisted);
    let zoom = clampZoom(persisted?.zoom ?? this.getSettings().defaultZoom / 100), panX = persisted?.panX ?? 0, panY = persisted?.panY ?? 0;
    let naturalWidth = 0, naturalHeight = 0, dragging = false, lastX = 0, lastY = 0;
    const isReadingMode = (): boolean => !!shell.closest(".markdown-preview-view");
    const closePanel = (): void => { panel.hidden = true; menu.setAttribute("aria-expanded", "false"); menu.removeAttribute("data-open"); };
    const updateMode = (): void => { const reading = isReadingMode(); shell.dataset.mode = reading ? "reading" : "writing"; controls.hidden = reading; if (reading) { dragging = false; closePanel(); } };
    const persistViewState = (): void => { const state = { zoom, panX, panY }; TikzRendererView.viewStates.set(stateKey, state); saveViewState(stateKey, state); };
    const positionPanel = (): void => { if (panel.hidden || !shell.isConnected || isReadingMode()) return; const b = menu.getBoundingClientRect(); const vw = win?.innerWidth ?? doc.documentElement.clientWidth; const vh = win?.innerHeight ?? doc.documentElement.clientHeight; const width = Math.min(270, Math.max(230, vw - 16)); panel.style.width = `${width}px`; const r = panel.getBoundingClientRect(); let left = b.left; let top = b.bottom + 6; if (left + r.width > vw - 8) left = Math.max(8, vw - r.width - 8); if (left < 8) left = 8; if (top + r.height > vh - 8) top = b.top - r.height - 6; if (top < 8) top = 8; panel.style.left = `${Math.round(left)}px`; panel.style.top = `${Math.round(top)}px`; };
    const applyTheme = (): void => { const s = this.getSettings(); const theme = s.displayTheme === "auto" ? detectTheme(doc) : s.displayTheme; shell.dataset.theme = theme; if (theme === "custom") { shell.style.setProperty("--tikz-custom-bg", s.customBackgroundColor); shell.style.setProperty("--tikz-custom-bg-opacity", `${s.customBackgroundOpacity / 100}`); } else { shell.style.removeProperty("--tikz-custom-bg"); shell.style.removeProperty("--tikz-custom-bg-opacity"); } };
    const ensureIntrinsicSize = (): boolean => { if (naturalWidth > 0 && naturalHeight > 0) return true; const b = svg.viewBox?.baseVal; if (b && b.width > 0 && b.height > 0) { naturalWidth = b.width; naturalHeight = b.height; return true; } const w = Number.parseFloat(svg.getAttribute("width") ?? ""); const h = Number.parseFloat(svg.getAttribute("height") ?? ""); if (w > 0 && h > 0) { naturalWidth = w; naturalHeight = h; return true; } return false; };
    const applyZoom = (): void => { ensureIntrinsicSize(); if (naturalWidth > 0 && naturalHeight > 0) { svg.style.width = `${naturalWidth * zoom}px`; svg.style.height = `${naturalHeight * zoom}px`; svg.style.maxWidth = "none"; } svg.style.transform = `translate3d(${panX}px, ${panY}px, 0)`; viewport.classList.toggle("is-pannable", !isReadingMode() && zoom > 1); viewport.classList.toggle("is-dragging", dragging); viewport.style.touchAction = isReadingMode() ? "auto" : zoom > 1 ? "none" : "pan-y"; applyTheme(); updateMode(); positionPanel(); };
    const resetView = (): void => { if (isReadingMode()) return; zoom = clampZoom(this.getSettings().defaultZoom / 100); panX = 0; panY = 0; persistViewState(); applyZoom(); };
    const fit = (): void => { if (isReadingMode() || !ensureIntrinsicSize()) return; const width = Math.max(1, this.containerEl.clientWidth); zoom = clampZoom(Math.min(1, width / naturalWidth)); panX = 0; panY = 0; persistViewState(); applyZoom(); };
    const addButton = (label: string, action: () => void | Promise<void>): void => { const b = panel.createEl("button", { text: label, attr: { type: "button", role: "menuitem" } }); b.addEventListener("click", e => { e.preventDefault(); e.stopPropagation(); void action(); }); };
    const showAssetActions = (): void => { const path = this.result.assetPath; if (!path) return; const links = panel.createDiv({ cls: "tikz-renderer-asset-links" }); links.createEl("a", { text: `SVG: ${path}`, attr: { href: "#" } }).addEventListener("click", e => { e.preventDefault(); this.app.workspace.openLinkText(path, this.sourcePath, false); }); links.createEl("button", { text: "Copy SVG wikilink", attr: { type: "button" } }).addEventListener("click", async e => { e.preventDefault(); e.stopPropagation(); await navigator.clipboard.writeText(`[[${path}]]`); new Notice("SVG wikilink copied."); }); };
    const renderThemeMenu = (): void => { panel.empty(); panel.createDiv({ cls: "tikz-renderer-panel-title", text: "Theme" }); const themes: Array<[DisplayTheme, string]> = [["auto", "Auto"], ["obsidian", "Obsidian"], ["light", "Light"], ["paper", "Paper"], ["dark", "Dark"], ["contrast", "Contrast"], ["bw", "Black & white"], ["custom", "Custom"]]; for (const [theme, label] of themes) { const b = panel.createEl("button", { text: label, attr: { type: "button", role: "menuitemradio", "aria-checked": `${this.getSettings().displayTheme === theme}` } }); b.addEventListener("click", async e => { e.preventDefault(); e.stopPropagation(); await this.saveSettings({ ...this.getSettings(), displayTheme: theme }); applyTheme(); if (theme === "custom") renderThemeMenu(); else closePanel(); }); } if (this.getSettings().displayTheme === "custom") { const color = panel.createEl("input", { attr: { type: "color", value: this.getSettings().customBackgroundColor } }); color.addEventListener("change", async () => { await this.saveSettings({ ...this.getSettings(), customBackgroundColor: color.value }); applyTheme(); }); const opacity = panel.createEl("input", { attr: { type: "range", min: "10", max: "100", value: `${this.getSettings().customBackgroundOpacity}` } }); opacity.addEventListener("input", () => shell.style.setProperty("--tikz-custom-bg-opacity", `${Number(opacity.value) / 100}`)); opacity.addEventListener("change", async () => this.saveSettings({ ...this.getSettings(), customBackgroundOpacity: Number(opacity.value) })); } panel.createEl("button", { text: "Back", attr: { type: "button" } }).addEventListener("click", e => { e.preventDefault(); e.stopPropagation(); buildMainPanel(); }); positionPanel(); };
    const buildMainPanel = (): void => { panel.empty(); panel.createDiv({ cls: "tikz-renderer-panel-title", text: "TikZ controls" }); addButton("Zoom −", () => { if (isReadingMode()) return; zoom = clampZoom(zoom - .25); persistViewState(); applyZoom(); }); addButton("Zoom +", () => { if (isReadingMode()) return; zoom = clampZoom(zoom + .25); persistViewState(); applyZoom(); }); addButton("Reset view", resetView); addButton("Fit", fit); addButton("Theme", renderThemeMenu); addButton("Edit source", () => new TikzSourceModal(this.app, this.source, async next => this.editSource(next)).open()); addButton("History", () => { panel.empty(); panel.createDiv({ cls: "tikz-renderer-panel-title", text: "History" }); const entries = this.history.list(this.historyKey); for (const [i, entry] of entries.entries()) { const row = panel.createDiv({ cls: "tikz-history-row" }); row.createSpan({ text: `Version ${entries.length - i}` }); row.createSpan({ text: new Date(entry.timestamp).toLocaleString() }); if (entry.source !== this.source) row.createEl("button", { text: "Restore", attr: { type: "button" } }).addEventListener("click", () => new TikzSourceModal(this.app, entry.source, async next => this.editSource(next)).open()); } panel.createEl("button", { text: "Back", attr: { type: "button" } }).addEventListener("click", () => buildMainPanel()); }); addButton("Re-render", async () => { const next = await this.service.render(this.source, this.kind); this.result.svg = next.svg; this.result.hash = next.hash; this.result.engine = next.engine; this.result.fromCache = next.fromCache; this.result.assetPath = await this.exportService.saveSvg(next.svg, next.hash, this.sourcePath, false); closePanel(); this.render(); }); addButton("Copy source", async () => { await navigator.clipboard.writeText(this.source); new Notice("TikZ source copied."); }); if (this.result.assetPath) showAssetActions(); };
    const openPanel = (): void => { if (!shell.isConnected || controls.hidden || isReadingMode()) return; panel.hidden = false; menu.setAttribute("aria-expanded", "true"); menu.setAttribute("data-open", "true"); buildMainPanel(); positionPanel(); };
    const togglePanel = (e: Event): void => { e.preventDefault(); e.stopPropagation(); if (isReadingMode()) return; if (panel.hidden) openPanel(); else closePanel(); };
    menu.addEventListener("pointerdown", togglePanel); menu.addEventListener("keydown", e => { if ((e.key === "Enter" || e.key === " ") && !isReadingMode()) togglePanel(e); });
    const outsidePointerDown = (e: PointerEvent): void => { if (!panel.hidden && (!(e.target instanceof Node) || (!shell.contains(e.target) && !panel.contains(e.target)))) closePanel(); }; doc.addEventListener("pointerdown", outsidePointerDown, true);
    const escape = (e: KeyboardEvent): void => { if (e.key === "Escape" && !panel.hidden) { closePanel(); menu.focus(); } }; doc.addEventListener("keydown", escape, true);
    svg.addEventListener("click", e => { e.preventDefault(); e.stopPropagation(); });
    viewport.addEventListener("pointerdown", e => { if (isReadingMode() || e.button !== 0 || zoom <= 1) return; dragging = true; lastX = e.clientX; lastY = e.clientY; viewport.setPointerCapture(e.pointerId); viewport.classList.add("is-dragging"); e.preventDefault(); });
    viewport.addEventListener("pointermove", e => { if (!dragging || isReadingMode()) return; panX += e.clientX - lastX; panY += e.clientY - lastY; lastX = e.clientX; lastY = e.clientY; svg.style.transform = `translate3d(${panX}px, ${panY}px, 0)`; e.preventDefault(); });
    const stopDragging = (): void => { if (!dragging) return; dragging = false; persistViewState(); viewport.classList.remove("is-dragging"); }; viewport.addEventListener("pointerup", stopDragging); viewport.addEventListener("pointercancel", stopDragging); viewport.addEventListener("lostpointercapture", stopDragging);
    const wheel = (e: WheelEvent): void => { if (isReadingMode() || (!e.ctrlKey && !e.metaKey) || !shell.isConnected) return; const target = e.target; if (!(target instanceof Node) || !viewport.contains(target)) return; if (target instanceof HTMLInputElement || target instanceof HTMLButtonElement) return; if (!ensureIntrinsicSize()) return; e.preventDefault(); e.stopPropagation(); const old = zoom; const next = clampZoom(old * (e.deltaY < 0 ? 1.12 : 1 / 1.12)); if (next === old) return; const r = viewport.getBoundingClientRect(); const x = e.clientX - r.left; const y = e.clientY - r.top; const ratio = next / old; panX = x - (x - panX) * ratio; panY = y - (y - panY) * ratio; zoom = next; persistViewState(); applyZoom(); };
    win?.addEventListener("wheel", wheel, { passive: false, capture: true });
    const observer = new MutationObserver(() => { updateMode(); applyTheme(); positionPanel(); }); observer.observe(doc.body, { attributes: true, attributeFilter: ["class"] });
    const resizeObserver = new ResizeObserver(() => positionPanel()); resizeObserver.observe(viewport);
    const reposition = (): void => positionPanel(); win?.addEventListener("scroll", reposition, true); win?.addEventListener("resize", reposition);
    buildMainPanel(); closePanel(); updateMode(); applyTheme(); ensureIntrinsicSize(); applyZoom();
    this.cleanup = () => { persistViewState(); doc.removeEventListener("pointerdown", outsidePointerDown, true); doc.removeEventListener("keydown", escape, true); menu.removeEventListener("pointerdown", togglePanel); win?.removeEventListener("wheel", wheel, true); win?.removeEventListener("scroll", reposition, true); win?.removeEventListener("resize", reposition); observer.disconnect(); resizeObserver.disconnect(); closePanel(); panel.remove(); if (TikzRendererView.activeViews.get(stateKey) === this) TikzRendererView.activeViews.delete(stateKey); TikzRendererView.allViews.delete(this); this.cleanup = undefined; };
  }
  onunload(): void { this.cleanup?.(); this.containerEl.empty(); }
  dispose(emptyContainer = true): void { this.cleanup?.(); if (emptyContainer && this.containerEl.isConnected) this.containerEl.empty(); }
  static disposeAll(): void { for (const view of Array.from(this.allViews)) view.dispose(true); this.activeViews.clear(); this.allViews.clear(); }
}

function detectTheme(doc: Document): string { if (doc.body.classList.contains("theme-dark")) return "dark"; if (doc.body.classList.contains("theme-light")) return "light"; return "obsidian"; }
function clampZoom(value: number): number { return Math.min(5, Math.max(.25, value)); }
function viewStorageKey(key: string): string { return `obsidian-tikz-renderer:view:${key}`; }
function loadViewState(key: string): TikzViewState | undefined { try { const raw = window.localStorage.getItem(viewStorageKey(key)); if (!raw) return undefined; const p = JSON.parse(raw) as Partial<TikzViewState>; if (!Number.isFinite(p.zoom) || !Number.isFinite(p.panX) || !Number.isFinite(p.panY)) return undefined; return { zoom: clampZoom(Number(p.zoom)), panX: Number(p.panX), panY: Number(p.panY) }; } catch { return undefined; } }
function saveViewState(key: string, state: TikzViewState): void { try { window.localStorage.setItem(viewStorageKey(key), JSON.stringify(state)); } catch { /* storage may be unavailable */ } }

class TikzSourceModal extends Modal {
  constructor(app: App, private readonly initialSource: string, private readonly onRender: (source: string) => Promise<void>) { super(app); }
  onOpen(): void { this.titleEl.empty(); this.contentEl.empty(); const editor = this.contentEl.createEl("textarea", { cls: "tikz-source-editor" }); editor.value = this.initialSource; editor.spellcheck = false; const actions = this.contentEl.createDiv({ cls: "tikz-source-actions" }); actions.createEl("button", { text: "Cancel", attr: { type: "button" } }).addEventListener("click", () => this.close()); actions.createEl("button", { text: "Render", attr: { type: "button" } }).addEventListener("click", async () => { try { await this.onRender(editor.value); this.close(); } catch (error) { new Notice(error instanceof Error ? error.message : String(error), 8000); } }); editor.focus(); }
}
